#!/bin/sh

mkdir /cgroup/cp
echo $$ > /cgroup/cp/tasks
echo 500 > /cgroup/cp/blkio.weight

cp /dev/zero /fs/zero-cg1-cp &

mkdir /cgroup/dd
echo $$ > /cgroup/dd/tasks
echo 1000 > /cgroup/dd/blkio.weight

dd if=/dev/zero of=/fs/zero-cg2-dd1 bs=64k &
dd if=/dev/zero of=/fs/zero-cg2-dd2 bs=64k &

