#!/bin/sh

mkdir /cgroup/cp
echo $$ > /cgroup/cp/tasks

dd if=/dev/zero of=/fs/zero-1M bs=1M oflag=direct conv=fsync &

mkdir /cgroup/dd
echo $$ > /cgroup/dd/tasks

dd if=/dev/zero of=/fs/zero-64k bs=64k oflag=direct conv=fsync &

mkdir /cgroup/ddd
echo $$ > /cgroup/ddd/tasks

dd if=/dev/zero of=/fs/zero-4k  bs=4k  oflag=direct conv=fsync &
