#!/bin/sh

mkdir /cgroup/cp
echo $$ > /cgroup/cp/tasks

dd if=/dev/zero of=/fs/zero-cg1-dd1 bs=1M oflag=direct &
dd if=/dev/zero of=/fs/zero-cg1-dd2 bs=1M oflag=direct &
dd if=/dev/zero of=/fs/zero-cg1-dd3 bs=1M oflag=direct &

mkdir /cgroup/dd
echo $$ > /cgroup/dd/tasks

dd if=/dev/zero of=/fs/zero-cg2-dd1 bs=1M oflag=direct &
dd if=/dev/zero of=/fs/zero-cg2-dd2 bs=1M oflag=direct &
dd if=/dev/zero of=/fs/zero-cg2-dd3 bs=1M oflag=direct &

