#!/bin/sh

mkdir /cgroup/cp
echo $$ > /cgroup/cp/tasks
echo 1000 > /cgroup/cp/blkio.weight

dd if=/dev/zero of=/fs/zero-cg1-dd-direct bs=64k oflag=direct &
cp /dev/zero /fs/zero-cg1-cp &

mkdir /cgroup/dd
echo $$ > /cgroup/dd/tasks
echo 1000 > /cgroup/dd/blkio.weight

dd if=/dev/zero of=/fs/zero-cg2-dd-direct bs=64k oflag=direct &
dd if=/dev/zero of=/fs/zero-cg2-dd        bs=64k &
