#!/bin/sh

mkdir /cgroup/cp
echo $$ > /cgroup/cp/tasks

dd if=/dev/zero of=/fs/zero-cg1-dd-direct bs=64k oflag=direct &
cp /dev/zero /fs/zero-cg1-cp &

mkdir /cgroup/dd
echo $$ > /cgroup/dd/tasks

dd if=/dev/zero of=/fs/zero-cg2-dd-direct bs=64k oflag=direct &
dd if=/dev/zero of=/fs/zero-cg2-dd        bs=64k &

mkdir /cgroup/ddd
echo $$ > /cgroup/ddd/tasks

dd if=/dev/zero of=/fs/zero-cg3-dd-direct bs=64k oflag=direct &
dd if=/dev/zero of=/fs/zero-cg3-dd        bs=64k &
