#!/bin/sh

rsync -qptg * snb:io-controller-tests

ssh root@snb "mount /dev/disk/by-id/ata-WDC_WD1002FAEX-00Z3A0_WD-WCATR5431916-part7 /fs 2>/dev/null; $HOME/io-controller-tests/run $*"

rsync -a snb:io-controller-tests/log/*.`date +%F`-* log/
